package enums

const (
	STATUS_OK                    = "OK"
	STATUS_CREATED               = "CREATED"
	STATUS_ACCEPTED              = "ACCEPTED"
	STATUS_NO_CONTENT            = "NO_CONTENT"
	STATUS_MOVED_PERMANENTLY     = "MOVED_PERMANENTLY"
	STATUS_FOUND                 = "FOUND"
	STATUS_NOT_MODIFIED          = "NOT_MODIFIED"
	STATUS_TEMPORARY_REDIRECT    = "TEMPORARY_REDIRECT"
	STATUS_PERMANENT_REDIRECT    = "PERMANENT_REDIRECT"
	STATUS_BAD_REQUEST           = "BAD_REQUEST"
	STATUS_UNAUTHORIZED          = "UNAUTHORIZED"
	STATUS_FORBIDDEN             = "FORBIDDEN"
	STATUS_NOT_FOUND             = "NOT_FOUND"
	STATUS_METHOD_NOT_ALLOWED    = "METHOD_NOT_ALLOWED"
	STATUS_CONFLICT              = "CONFLICT"
	STATUS_INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
	STATUS_SERVICE_UNAVAILABLE   = "SERVICE_UNAVAILABLE"
	STATUS_GATEWAY_TIMEOUT       = "GATEWAY_TIMEOUT"
)
